apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-adexchangebuyer-exporter
spec:
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9835"
        prometheus.io/scrape: "true"
