apiVersion: v1
kind: Service
metadata:
  name: google-adexchangebuyer-exporter
  labels:
    app: google-adexchangebuyer-exporter
spec:
  ports:
    - name: metrics
      port: 9835
      protocol: TCP
      targetPort: 9835
  selector:
    app: google-adexchangebuyer-exporter
