apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: google-adexchangebuyer-exporter
  name: google-adexchangebuyer-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-adexchangebuyer-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: google-adexchangebuyer-exporter
    spec:
      serviceAccountName: google-adexchangebuyer-exporter
      containers:
        - name: google-adexchangebuyer-exporter
          image: probablynot/google-adexchangebuyer-exporter:latest
          command: ["./google-adexchangebuyer-exporter"]
          args:
            - --google.service-account=$(GOOGLE_SERVICE_ACCOUNT)
            - --google.bidder-id=$(GOOGLE_BIDDER_ID)
          envFrom:
            - secretRef:
                name: google-adexchangebuyer-exporter
          resources: {}
          ports:
            - name: metrics
              containerPort: 9835
              protocol: TCP
